### ISSUE TITLE
syntax definitions don't propagate into fasl files

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#101]
**Reported by: pnkfelix  on Mon Jun 12 03:04:23 2006**
Consider the following interactions with Larceny, where ```foo.sch``` just contains syntax definition:
```(define-syntax bazzle (syntax-rules () ((bazzle) 'basil)))```

```
% larceny
> (compile-file "foo.sch")
> (exit)

% larceny
> (load "foo.sch")
> (bazzle)
'basil
> (exit)

% larceny
> (load "foo.fasl")
> (bazzle)

Error: Reference to undefined global variable "bazzle".
```

The fasl file and the sch file have different effects when you load them.  This essentially implies that users have to be very careful about when they compile files that contain syntax definitions.  (Perhaps this was a deliberate design choice, but PnkFelix sees it as a bug).

PnkFelix is working around this problem for his designs on ExtendingRequire, but it would be a good thing to think about fixing in general.

**Comment by WillClinger** [comment]
Now that we have the R7RS as well as the R6RS, Larceny's R5RS serves only two groups of users:
* Larceny developers
* folks who have been using Larceny's R5RS mode for a long time
Both groups have learned to live with the problem.  We should focus on R7RS.
