### ISSUE TITLE
R5RS tests

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#11]
**Reported by: tov  on Mon Feb 13 18:40:41 2006**
We're still using Jaffer's R4RS tests.  Is there an R5RS test suite we could adapt and use?

**Comment by WillClinger** [comment]
R7RS section 4.2.2 says:

> Another restriction is that it is an error to invoke the continuation of an ⟨init⟩ more than once.

We are moving on from R5RS (except as a base platform for R7RS), so we can close this.
