### ISSUE TITLE
Sparc call expressions limited to < 1024 args

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#234]
**Reported by: lth  on Wed Jul 23 06:00:00 1997**
034  v0.28f (970723 / lth)
Priority: very low.
Category: SPARCASM / correctness

The number of arguments in a procedure call expression is limited to 
1023.  This is due to the way the argument count is set up during 
INVOKE and the way it is compared during ARGS=, ARGS>=.

Note that expressions like (apply + massively-long-list) still work,
because + takes 0 or more arguments (so the comparison is with 0), and
apply computes the correct length of the list.  It is only a syntactic
call expression that is so limited.

This is easy to fix, and the fix does not impact code that has no
more than 1023 arguments in a call.

The compiler does in fact emit an 'invoke n' instruction for even 
large n, so this is a real bug.

**Comment by WillClinger** [comment]
We are dropping support for Sparc, so I'm closing this.
