### ISSUE TITLE
lambda et al are not reserved words

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#283]
**Reported by: lth  on Tue Dec 15 06:00:00 1998**
083 v0.38 (981215 / lth)
Priority: medium.
Category: TWOBIT / correctness
See also: #291

Bugs w.r.t. R4RS, R5RS, or the IEEE standard:

* some top-level names are reserved by the macro expander:
 lambda, define, quote, begin, if, set!

* some top-level names are reserved by the quasiquote macro:
 lambda, define, quote, begin, if, set!

**Comment by WillClinger** [comment]
This was fixed years ago.
