### ISSUE TITLE
Space leaks can result from dead variables in registers or in

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#313]
**Reported by: wdc  on Fri Oct 16 06:00:00 1998**
113 v0.34 (981016 / wdc)
Priority: medium
Category: TWOBIT / quality-of-implementation

Space leaks can result from dead variables in registers or in
the stack.

**Comment by WillClinger** [comment]
The `avoid-space-leaks` parameter, which is displayed by `compiler-switches`, instructs the compiler to generate code that won't have space leaks.

So it looks this was fixed years ago.
