### ISSUE TITLE
Space leaks can result from dead variables in closures.

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#314]
**Reported by: wdc  on Fri Oct 16 06:00:00 1998**
114 v0.34 (981016 / wdc)
Priority: low
Category: TWOBIT / quality-of-implementation

Space leaks can result from dead variables in closures.

**Comment by WillClinger** [comment]
Pretty sure this was fixed years ago, but that should be checked.  If fixed, this issue should be closed.

**Comment by WillClinger** [comment]
For several years now, Larceny normally generates code for flat closures that do not close over dead variables.

There is an `avoid-space-leaks` compiler switch that is apparently being ignored.  I believe its purpose was to force generation of code that zeroes dead argument registers at every procedure call, but not doing that is unlikely to be a significant source of space leaks.  In any case, implementing or eliminating that compiler switch should be a separate issue.
