### ISSUE TITLE
pretty print of records, and pretty print formatting.

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#339]
**Reported by: lth  on Sat Oct 23 06:00:00 1999**
139 v0.46 (991023 / lth)
Priority: medium.
Category: Pretty printer / correctness

(1) Records (defined with make-record-type et al in Auxlib/record.sch)
   are no longer displayed with the record type printer; it just displays
   "#<STRUCTURE>".

   The pretty printer does not use the structure printer to print 
   structures.   Fixing this will probably require changing the semantics
   of the structure printer, which now has no notion of "layout".

(2) The pretty printer does not format very well; in particular, it formats
   things vertically that could be formatted horizontally.  Try:

     (pretty-print ((system-function 'sys$get-resource-usage)))

   for some pretty-line-length values; when I tried I could not get it to
   print the remset entries horizontally even with line length 150 when 
   all the lines fit on 100 characters.

**Comment by WillClinger** [comment]
The first problem was fixed years ago.

The second problem should be classified as a desired enhancement, not a defect, and should be a separate issue.

Since the real defect has been fixed, I'm closing this.
