### ISSUE TITLE
There is no way to seed the random number generator, and it doesn't

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#350]
**Reported by: lth  on Wed Nov 24 06:00:00 1999**
150 v0.48 (991124 / lth)
Priority: low
Category: Language / usefulness

There is no way to seed the random number generator, and it doesn't
auto-seed on startup, so we get the same sequence every execution
of the system.

**Comment by WillClinger** [comment]
SRFI 27 allows programmers to set the seed, and I expect an R7RS (large) library will do so as well.

It's pretty easy to implement a seed-settable pseudo-random number generator on top of Larceny's `random`, and some entropy can be extracted from `current-seconds` and other sources of entropy.

We have to draw the line somewhere, or we'll end up reimplementing SRFI 27.  The easiest way to draw the line is by not providing a Larceny-specific alternative that would compete with SRFI 27 and other standards.
