### ISSUE TITLE
Provide public access to nightly builds

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#396]
**Reported by: tov  on Wed Jan 17 11:13:46 2007**
We are doing nightly builds now, so we should provide a way for users to download them, so they can benefit from our latest features without having to build Larceny themselves.

**Comment by WillClinger** [comment]
http://larceny.ccs.neu.edu/nightly/ now links to binary distributions of nightly builds for native Larceny on Linux and OS X (both Intel).  It could easily be made to link to nightly builds for Windows, if such there were.
