### ISSUE TITLE
parameterize writer output format

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#478]
**Reported by: pnkfelix  on Thu Oct 18 11:32:14 2007**
Will [https://lists.ccs.neu.edu/pipermail/larceny-users/2007-October/000149.html writes:]

```
Larceny will accept @ as a symbol when the reader
is in #!larceny mode, but Larceny's output routines
currently try to print all symbols with enough
escapes so they can be read back in no matter what
the reader mode.  We probably should add a switch
that tells the output routines they don't have to
do that, but that switch isn't likely to be added
until v0.96.
```

**Comment by WillClinger** [comment]
As of ed8da1b82eee2989398b5fa1db7091a6a4ece803, textual output ports have a port-specific flag that tells the output routines which syntaxes to use.  This will work in v0.98.
