### ISSUE TITLE
document (and redistribute) Solaris autobuilds

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#507]
**Reported by: pnkfelix  on Tue Nov 20 14:36:30 2007**
Will and PnkFelix agreed today that we should redistribute the Solaris autobuilds so that the default builds will occur on one machine, and the PetitLarceny builds will occur on a different machine.  That way we will get feedback on the Petit builds earlier (probably about 2 hours earlier, which means around 11:30 AM instead of 1:30 PM, which can make the difference in terms of whether a bug is noticed and fixed in time for the next night's builds.)

Since this task needs to happen and will need to be registered on two distinct crontabs on the CCIS machines, Will and PnkFelix also agreed that it might as well be a setup where we put one of the builds on a crontab of Will's, and the other build on PnkFelix's crontab.  That way Will will know how to maintain the autobuilds in the future.

**Comment by WillClinger** [comment]
We no longer have access to any operable Sparc machines.  Larceny v0.97 will be our last release for the Sparc.
