### ISSUE TITLE
SRO should be added to larceny test suite

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#522]
**Reported by: pnkfelix  on Tue Jan 15 16:26:35 2008**
I got a bit of an embarrassment with Will today when he tried to use `sro` with the regional collector and it broke.

The fix was easy, but to prevent this happening in the future, we should exercise `sro` as part of our tests (perhaps it belongs in the library tests...)

(There is of course also the question of how one properly "tests" that sro is working.  But even just running it a couple of times would have caught the problem I had.)

**Comment by WillClinger** [comment]
The `sro` procedure is used to implement SRFI 124, which is used to implement the `(scheme ephemeron)` library of R7RS Red Edition, which is tested by the R7RS tests.

That's sort of indirect, but it should be good enough for now.
