### ISSUE TITLE
PIC and Stack Execution problems

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#541]
**Reported by: pnkfelix  on Wed May 21 23:36:15 2008**
Austen Dicken points out the following issues:

> I wanted to let you know that the current build of Larceny, v0.961, has
> some issues upon its compile.  Namely, it is currently compiled without
> the PIC option, causing a few TEXTREL references in the resulting
> binaries that can cause resulting binary to not be as cross-compatible
> as it can be.  This is the same case with a few of the assembly calls,
> where the compiler creates executable stack space.
> 
> I have attached a patch for each of the aforementioned issues that
> appear to solve the problem.  Let me know if there is any other
> information you would like.  I hope these patches help.

When I asked Austen what host environment he was using that reveals these problems, he replied with the following information:

> The build environment was an x86 running Gentoo Linux on a pentium
> processor.  It was found that the PIC problems occurred when petit
> larceny was built, and the stack execution problems occurred when native
> larceny was built.
> 
> Basically, the only reason I was able to detect it was because the
> automatic Gentoo QA system scans all executables prior to installing
> them for problems like pre-stripping of symbols, PIC errors, and Stack
> Execution errors.  The system alerted me to the issue when I was trying
> to create the ebuild (Gentoo Package) for the program.
> 
> If you have any other questions that may be helpful, please let me know.

**Comment by WillClinger** [comment]
Those patches were applied in changeset f20ec6b34492803670ae75bb96dc5d13c6d3a985
