### ISSUE TITLE
case sensitivity modes when loading file via command line may surprise users

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#547]
**Reported by: pnkfelix  on Mon Jun 30 16:39:04 2008**
While running the heap building script for Larceny, I ran into some surprising undefined global variable errors when some of the FFI files had been updated (and thus were being loaded from source) while others were still being loaded from fasl files.

The errors looked like this:

```
% ./larceny.bin -stopcopy -- src/Build/iasn-larceny-heap.sch 
...
Warning: loading source in favor of stale fasl file: /Users/pnkfelix/larcenytest/larceny-gcbench/larceny_src/lib/Ffi/ffi-i386.sch


Error: Undefined global variable "ffi/i386-C-callout-cdecl".
Entering debugger; type "?" for help.
debug> 
```

The heap building script is run on top of the bootstrap heap, usually via the invocation `larceny.bin -stopcopy` followed by loading the heap build script via a command line parameter.

There were a couple of things that surprised me:
- loading the heap building script via the REPL worked, while loading the script via the command line broke (as illustrated at the top of the ticket).
- my initial attempts to make a small test case to expose the problem failed, because I tried to replicate the problem using the full fledged larceny.heap, rather than the bootstrap heap.

At this point, I believe I understand where the behavior is coming from (I think its from the fact that [source:trunk/larceny_src/src/Lib/Common/main.sch main.sch] adjusts the case sensitivity '''after''' invoking `failsafe-process-arguments`).  

Here is a transcript of interactions with a larceny executable that illustrate the weirdness.  (The fourth load of `foo.sch` is the one that I am worried about users being confused by.)

```
% cat foo.sch
(define Hello-World 'hELLO-wORLD!)

(display Hello-World)
(newline)

(exit)
% ./larceny
Larceny v0.961 "Fluoridation" (Jun 30 2008 15:52:46, precise:Posix Unix:unified)
larceny.heap, built on Mon Jun 30 16:36:29 EDT 2008

> (load "foo.sch")
hELLO-wORLD!
% ./larceny -- foo.sch
Larceny v0.961 "Fluoridation" (Jun 30 2008 15:52:46, precise:Posix Unix:unified)
hELLO-wORLD!
% ./larceny.bin
LARCENY_ROOT not set; using current directory
Larceny v0.961 "Fluoridation" (Jun 30 2008 15:52:46, precise:Posix Unix:unified)

> (load "foo.sch")
hELLO-wORLD!
% ./larceny.bin -- foo.sch
LARCENY_ROOT not set; using current directory
Larceny v0.961 "Fluoridation" (Jun 30 2008 15:52:46, precise:Posix Unix:unified)
hello-world!
% 
```

This is not a huge issue, since I do not expect the average user to be doing anything starting from the bootstrap heap; if the system starts from the larceny.heap, then it starts with that heap's case sensitivity mode when loading files via the command line arguments.

But it is an issue for the heap building scripts like [source:trunk/larceny_src/src/Build/iasn-larceny-heap.sch iasn-larceny-heap.sch] or [source:trunk/larceny_src/src/Build/sparc-larceny-heap.sch sparc-larceny-heap.sch].
(After all, what sparked the problem for me initially were issues with the FFI .sch files being loaded in case-insensitive mode while the other FFI .sch files had been compiled in case-sensitive mode.)

I am currently planning to work around this problem by adding `no-fold-case` directives to the FFI source code, so that those files will continue to define their identifiers in a case-sensitive manner even when loaded from source.  (It would also guard against the files being mis-compiled by a compiler that happens to be running in case-insensitive mode.)  So that will be a band-aid for the problem with respect to the FFI source code.  (Another fix would be to remove all case-sensitive identifiers from our libraries, but that is a questionable strategy for fixing this sort of thing.)

But we (that is, Will) may want to consider moving the invocation of `adjust-case-sensitivity!` above the loads of the init files and command line argument processing.  (Additionally, the way things are structured now, a user's attempt to change the default case-sensitivity in a personal init file will be foiled by the subsequent invocation of `adjust-case-sensitivity!`)

**Comment by WillClinger** [comment]
For Common Larceny, I think `failsafe-process-arguments` needs to be called before `adjust-case-sensitivity!`, because the command-line options that determine case sensitivity have to be parsed before the adjustment is made, and Common Larceny does that parsing in `failsafe-process-arguments`.

For everything but Common Larceny, that's the wrong order.

This matters only in R5RS mode, and only when no `--program` option is specified.

I'd like to move away from the `-- filename` hack.  The new `-r5 filename` idiom doesn't have this problem.  It will take us a couple of years to convert our scripts, however, because we shouldn't change the scripts until all of our development machines have upgraded to a v1.x version of Larceny.

There's an obvious patch for this problem: call `failsafe-process-arguments` first in Common Larceny, but call it after otherwise.  I'm hoping I can think of a more elegant solution.

**Comment by WillClinger** [comment]
Changeset 555678f810d6eded542a81eae3d373c2d79da871 implemented the obvious but ugly patch.
