### ISSUE TITLE
Parameterize compile-file over syntax environment and/or support srfi-55

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#56]
**Reported by: pnkfelix  on Thu Apr 20 11:08:15 2006**
The same way that you don't want to always use the ```(interaction-environment)``` with ```eval```, you don't always want to use the ''syntactic environment'' of the interaction environment with ```(compile-file ...)```.  Therefore, it would make sense to offer the option of allowing the user to pass in a different syntactic environment to use with ```compile-file```.  

Also, Twobit and Larceny have different semantics for how each of their versions of ```compile-file``` work, because each grabs a different syntactic environment for that role.  I think I understand why that makes sense for Twobit versus Larceny, but it also underscores why it really makes sense to allow the user to override whichever choice the compiler driver has made for the syntactic environment.

I honestly don't think that this change would help us acheive Flatt's "you want it when" semantics for modules directly, but I do suspect that the changes necessary to support this delta significantly overlap the changes to get "you want it when."

Something that might go along with this: a variant of ```load``` and/or ```require``` that produces a (first class) syntactic environment object, rather than mutations to your current environment.

**Comment by WillClinger** [comment]
The R7RS and R6RS solve this in a more general and more elegant manner.  We needn't spend more time on partial fixes for R5RS semantics.
