### ISSUE TITLE
cdash web presentation has false positives and does not include build logs

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#581]
**Reported by: pnkfelix  on Tue Aug  5 08:31:44 2008**
The windows builds have been failing for a while now.  (Unfortunately right now when a fatal error occurs, the autobuild machines pops up a dialog box asking if we want to send a bug report to microsoft, instead of just returning an error code and letting the script submit a log to the cdash server.)

Anyway, the cdash web presentation does not reflect this; after receiving the build logs, it claims that there were no build errors.  That's wrong.  (This problem is probably due to a mistake in how I am constructing the log file, though it could also be due to the fact that the larceny process is not returning an error code.  Not sure yet.)

Another semi-related problem is that while I submit full log information to the CDash server, the web frontend does not have any way for me to see the logs.  (This is probably due to inadequacies in the PHP code that constructs the CDash pages.  I probably am not going to attempt to fix it, except perhaps by encoding the logs in a manner that *will* be displayed by the server, e.g. as a series of errors and/or warning entries.)

**Comment by WillClinger** [comment]
As of v0.98 or thereabouts: Although we are still trying to create cdash-compatible XML files, we are no longer using cdash to report the results of nightly builds.

**Comment by pnkfelix** [comment]
Sad but true.  (Well,  only sad because to my knowledge no replacement system for presenting the continuous integration results was ever set up;  I certainly have no love for cdash itself)

**Comment by pnkfelix** [comment]
All the cool kids seem to be using [Travis](https://travis-ci.org/) for continuous integration testing atop github, so I'll open a ticket and look into how hard it would be to use them.

**Comment by pnkfelix** [comment]
Filed as #761
