### ISSUE TITLE
compile-stale-libraries compiles too many files

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#602]
**Reported by: will  on Sat Dec 27 13:34:25 2008**
Requested by Marco Maggi.

I cannot use `compile-stale-libraries`
when there are the following files in the same
directory:

```
compat.ikarus.sls
compat.larceny.sls
compat.ypsilon.sls
```

Larceny attempts to compile  all of them, not only
the "larceny.sls" one.

Will proposes we add a more selective version of
`compile-stale-libraries` that takes a list
of files that contain libraries or top-level
programs and compiles only the libraries on which
those files depend, and only if the libraries look
stale.

**Comment by WillClinger** [comment]
Workaround added by changeset a1d8e730ab4f3a626059fab8b05533464a4890de

The ```.larceny.sls``` hack is a hack, but it is now a more sensible hack.

There's more to be done, but I'm lowering the priority and changing the milestone.

**Comment by WillClinger** [comment]
We have added alternative facilities that compile fewer libraries and provide more control.
