### ISSUE TITLE
-fno-stack-protector flag breaks Sparc Petit build

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#639]
**Reported by: pnkfelix  on Mon Apr 27 10:41:19 2009**
Our Sparc Petit Larceny builds have been failing for a few nights.  Unfortunately the current CDash configuration does not allow one to easily access the build log files, but here's the relevant error message 
```
Creating final image in "petit.heap"...
gcc -c -ISys -I../../include -I../../include/Sys -I../../include/Shared  -O3 -DN
DEBUG2  -c -fno-stack-protector -falign-functions=4 -I../../include/Standard-C  
-o Sys/larceny.o Sys/larceny.c
cc1: unrecognized option `-fno-stack-protector'
make: *** [Sys/larceny.o] Error 1
```

Clearly changeset:6190 had a wider effect than I had intended.

(I had some nonsense written down about how this was not a gcc build, but it obviously is.)

The problem is probably that the version of gcc on the CCIS Solaris boxes is version 3.2.3, from 2002... so perhaps the makefile building system needs to be aware of the gcc version.  Or the makefile itself needs to query what version of gcc we are running.  Or we need to start using ```./configure``` as our users are clamoring for (but I am not eager to make such a change)

**Comment by WillClinger** [comment]
Now that our Sparc machine has died of bit rot, we can no longer support Sparc platforms.

We released v0.98 without a prebuilt version for PowerPC, and no one has complained about that.

So this issue has become irrelevant.  I'm closing it.
