### ISSUE TITLE
error messages should write data rather than display it

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#642]
**Reported by: pnkfelix  on Thu May  7 10:20:21 2009**
Our error messages can be confusing because they (sometimes?) use ```display``` instead of ```write``` to print data.

For example, consider the following:

```
Larceny v0.97a4 (alpha test) (May  6 2009 12:07:21, precise:Posix Unix:unified)
larceny.heap, built on Wed May  6 12:12:27 EDT 2009

> (vector-length "#(hi there)")


Error: Vector-length: #(hi there) is not a vector.
Entering debugger; type "?" for help.
debug> 
```

I do not see any drawback to using ```write``` rather than ```display``` for ''data'' (there may be an argument when it comes to other components of an error message).

**Comment by WillClinger** [comment]
Should be fixed by changeset af97cc115a67f2f16bc4974d4fd8799d3791f956
