### ISSUE TITLE
handling of final sigma in string-downcase

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#672]
**Reported by: will  on Thu Aug  4 09:30:59 2011**
From
http://lists.scheme-reports.org/pipermail/scheme-reports/2011-August/001256.html

Shiro Kawai gives this example:
```(string-downcase "ΧΑΟΣ.Σ") => "χαοσ.ς"```

Larceny behaves differently:
```(string-downcase "ΧΑΟΣ.Σ") => "χαος.σ"```

This should be determined by the word-breaking algorithm in UAX 29.

Will isn't sure which is right.  It's possible that UAX 29 has been changed since it was implemented in Larceny.

**Comment by WillClinger** [comment]
Fixed by changeset 0991ba147070b08fd2082a0ab666c1e89937acf5, which upgraded Larceny to Unicode 7.0.0.
