### ISSUE TITLE
SRFI 13 string-index-right

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#673]
**Reported by: t-guest  on Wed Oct 12 17:46:22 2011**
The SRFI 13 procedure string-index-right
don't respect the start argument.

For example
  (string-index-right "hello" #\h 1 5) => 0

Hint: replace (>= i 0) with (>= i start) in lib/SRFI/srfi-13.sch

**Comment by WillClinger** [comment]
Fixed by changeset b0e8c0fbf166964941bc90f35de48c8eae5872f2
