### ISSUE TITLE
The reader must flush the instruction cache across #^B bytevectors

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#675]
**Reported by: lth  on Tue Jul 24 14:37:15 2012**
The old reader would call sys$codevector-iflush on bytevectors read with the #^B syntax.  It appears that that functionality disappeared when the reader was rewritten.  Without it, FASL loading on architectures that don't keep data and instruction caches synchronized will be flaky or not work.

It is curious that this bug has not been discovered on Sparc, but in any case the ARM port does not work without a fix.

**Comment by WillClinger** [comment]
Looks as though Lars fixed this in changeset 8c73aef2db4c1bf62ad54c9c8a353f147c704379
