### ISSUE TITLE
link-lop must flush the instruction cache across code vectors

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#676]
**Reported by: lth  on Tue Jul 24 14:42:02 2012**
Asm/Shared/link-lop.sch converts certain Scheme data structures - usually the output of the in-memory compiler - to procedures.  When it processes code vectors it must flush the instruction cache for the addresses covered by the code vector, or Larceny on systems that have unsynchronized data and instruction caches will be flaky or broken.

This is probably a very old bug.  I have the code for Larceny 0.51 with link-lop.sch dated 23 November 1998 and the code does not flush the instruction cache.  It's remarkable that it was never discovered on Sparc, but in any case the ARM port will not work without the fix.

**Comment by WillClinger** [comment]
Looks as though Lars fixed this in changeset 8c73aef2db4c1bf62ad54c9c8a353f147c704379
