### ISSUE TITLE
bytevector-u8-set! needs a more compact error check

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#677]
**Reported by: lth  on Wed Aug  8 05:29:04 2012**
The expansion of bytevector-u8-set! turns out to be quite large, and the reason is that the macro definition is using a makeshift error handler:
```
`  ((_ larceny bytevector-u8-set! (bytevector-u8-set! x0 y0 z0))
    (let ((x x0)
          (y y0)
          (z z0))
#;    (.check! (.<:fix:fix z 256) ,$ex.bvset x y z)                     ; FIXME
#;    (.check! (.>=:fix:fix z 0) ,$ex.bvset x y z)                      ; FIXME
      (if (not (fx<=? 0 z 255))
          (begin (write (list 'bytevector-u8-set! x y z))
                 (newline)
                 (larceny-break)))
      (bytevector-set! x y z)))
```
This is related in some way to ticket #342, about the error checking around bytevector-set! in general.

**Comment by WillClinger** [comment]
Fixed by changeset abceeef8999a82321f1aadf05e567759a3394e7e
