### ISSUE TITLE
lset-difference with equal?

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#678]
**Reported by: t-guest  on Tue Oct 30 08:54:37 2012**
I'm getting (.97 windows, prebuilt, no flags):

(require 'srfi-1)
(lset-difference equal? '(a b c) '(d e a))
()

yet:

(lset-difference eq? '(a b c) '(d e a))
(b c)

**Comment by WillClinger** [comment]
The `(srfi :1)` library works correctly, so this is a problem only with R5RS mode.

**Comment by WillClinger** [comment]
R5RS version of SRFI 1 fixed by changeset 3fce93347c97c8d1de3098a0b4045237a90c8145
