### ISSUE TITLE
larcenists.org link to sassy is broken

### ISSUE THREAD

**Issue by pnkfelix** [larcenists/larceny#683]
The link to Sassy on http://www.larcenists.org/download.html still points to Earthlink. Sassy's current home seems to be http://sassy.sourceforge.net/ . 

(manually imported from: https://trac.ccs.neu.edu/trac/larceny/ticket/683 )

**Comment by WillClinger** [comment]
This (and many other broken links) were fixed by changeset fe143913ca9add295ef8d7866b5123db3aeb39f8
