### ISSUE TITLE
exit ignores argument

### ISSUE THREAD

**Issue by ashinn** [larcenists/larceny#722]
According to R7RS section 6.14 (exit #f) should terminate and return an exit value indicating failure to the operating system.  However, on OS X I get the following:

```bash
$ cat exit.scm 
(import (scheme process-context))
(exit #f)
$ larceny -r7rs -program exit.scm 
$ echo $?
0
```

When obj is a non-boolean exit should also try to return that value to the OS, e.g. returning integers in *nix or strings in Plan9.  Replacing #f with, e.g. 42 in the above program also results in a zero exit status.

**Comment by WillClinger** [comment]
Fixed by changeset 27fb63113e3d9e6ed31a688b09ea9e36821a53cc

This bug was introduced 27 January 2015 when changeset 9c9fe3fd18319df7b5dbc2f49b42080075c97ba6 implemented `emergency-exit`.  Today's changes added testing of the exit status to Larceny's R7RS test suite.
