### ISSUE TITLE
Some datums with datum labels cannot be parsed

### ISSUE THREAD

**Issue by mnieper** [larcenists/larceny#766]
For example, Larceny chokes on the following datum:
```
'(#0=#1=(a) #0#)
```

**Comment by mnieper** [comment]
I just noted that the error is based on the fact that one datum label follows another one. So currently, Larceny is simply not able to parse `#0=#1=<datum>`.

**Comment by WillClinger** [comment]
Fixed by changeset 11bba0f52a24c7506132d547882e88363ccd2276
