### ISSUE TITLE
`compile-stale` script does not recognize all of the syntax of the R7RS 

### ISSUE THREAD

**Issue by mnieper** [larcenists/larceny#774]
For example, `#\escape` in libraries definitions to be compiled yields a lexical error. Symbols of the form `|...|` are also unsupported.

Presumably, this is due to the `compile-stale` script requesting r6rs mode.

**Comment by WillClinger** [comment]
I suspect it's because all Scheme scripts run in ```-r6rs``` mode rather than ```-r7rs``` mode.

There's no good reason for that, because Scheme scripts were described only within an unratified appendix.

**Comment by mnieper** [comment]
Yes, it would be nice if a Larceny user could also turn their R7RS-programs into Scheme scripts.

**Comment by WillClinger** [comment]
Changing `scheme-script` to run scripts in R7RS mode appears to have fixed this.  See changeset 6ba1848584b6beaf6e0449087a83a0a2c00c32a5
