### ISSUE TITLE
Exporting mutable variables

### ISSUE THREAD

**Issue by mnieper** [larcenists/larceny#781]
Please see:

https://groups.google.com/forum/#!topic/comp.lang.scheme/UAnZyAe9pkg

Larceny's behaviour may or may not be a deviation from the R7RS.

**Comment by WillClinger** [comment]
Larceny's behavior appears to be allowed by the R7RS.  Changing Larceny's behavior would introduce an egregious incompatibility between R6RS and R7RS libraries.
