### ISSUE TITLE
Request for a fresh run of the R7RS Benchmarks

### ISSUE THREAD

**Issue by justinethier** [larcenists/larceny#785]
I would like to respectfully request a re-run of the R7RS benchmarks when you have a chance. Several updates have been released since the last run ~6 months ago, including Cyclone (now on 0.3.3 with significant performance improvements) and Sagittarius (there have been almost 20 releases).

**Comment by WillClinger** [comment]
Done 24 May 2017 in larcenists.github.io repository and pushed to web sites.

**Comment by justinethier** [comment]
Thanks @WillClinger
