### ISSUE TITLE
Inconsistent application of -fno-stack-protector

### ISSUE THREAD

**Issue by lars-t-hansen** [larcenists/larceny#809]
The build system passes `-fno-stack-protector` when compiling the runtime files but not when compiling the generated C code for Petit Larceny.  The problem is that the function `make-cflag-augment` in src/Rts/make-templates.sch is called only when building the former command line, but not when building the latter command line in `c-compiler:gcc-unix` in src/Asm/Standard-C/dumpheap-unix.sch.

Presumably an oversight since it's only an issue for Petit Larceny, and only when the Unix host enabled the stack protector by default, and even then perhaps only under some circumstances?

**Comment by WillClinger** [comment]
Possibly fixed by changeset dea55cb5745ee63a3bec33b3330256b047c420be

As a result of that change, Petit Larceny now requires gcc 4 or later.

**Comment by lars-t-hansen** [comment]
Definitely fixed by that changeset.
