### ISSUE TITLE
why did you make it so fckng hard to install. I dont know shell scripting, how am I supposed to install it?

### ISSUE THREAD

**Issue by BNTB** [larcenists/larceny#831]
can pls anybody help me to install this compiler? I've been struggling for half an hour now. am I supposed to learn shell scripting just to install this compiler?

**Comment by lassik** [comment]
Larceny hasn't been actively maintained (at least in public) for a few years. In particular, the compiler targets 32-bit CPUs only, not 64-bit. Unless you're experienced with both Scheme and Linux, it's best to start with a more popular Scheme implementation.

**Comment by BNTB** [comment]
Ye ima just use a compiler that compiles to C
