### ISSUE TITLE
Some tests don't pass -- why?

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#9]
**Reported by: tov  on Mon Feb 13 18:39:07 2006**
Let's figure out why some tests aren't passing, and then either do away with them or create a ticket here to fix the bug.  Having to ignore some tests makes testing as a whole less useful.

**Comment by WillClinger** [comment]
Changeset 03df1abf4d312fd59b73ca6bc9527ac2cfd987e5 fixed the `sqrt` test, and the problem with the regression test hasn't been showing up, so we're down to the one `exp` test with IasnLarceny.  I'm declaring this fixed and closing the issue.

It might be appropriate to open a new ticket just for the `exp` test.
