### ISSUE TITLE
Print circular structure in finite manner

### ISSUE THREAD

**Issue by larceny-trac-import** [larcenists/larceny#94]
**Reported by: pnkfelix  on Mon Jun  5 02:15:36 2006**
```
> (let ((x (cons 1 '()))) (set-cdr! x x) x)
```
will print an infinite structure.

We should consider adopting the common convention for printing circular data (```#1=```''EXP'' to establish and ```#1#``` to refer```) that other scheme implementations use.

**Comment by WillClinger** [comment]
The R7RS requires `write` to print circular structures using SRFI 38 notation.  This was implemented by changeset 5db8cfb8aad9451bd29f7ffc7fb0a77d55fbab39.

I'll close this ticket after I've fixed the pretty printer.  (For the pretty printer, I think I'll just parameterize the `print-length` and `print-level` parameters.)

**Comment by WillClinger** [comment]
Fixed by 480f2909935f4a7aa11ad701ab1d6e922e456152

The pretty printer still pretty much ignores `print-length` and `print-level`, but that's a different and less significant bug.
